// Code generated by mockery v2.20.0. DO NOT EDIT.

package http

import mock "github.com/stretchr/testify/mock"

// MockHandlerDependencyProvider is an autogenerated mock type for the HandlerDependencyProvider type
type MockHandlerDependencyProvider struct {
	mock.Mock
}

type MockHandlerDependencyProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandlerDependencyProvider) EXPECT() *MockHandlerDependencyProvider_Expecter {
	return &MockHandlerDependencyProvider_Expecter{mock: &_m.Mock}
}

// ArticleCategoryService provides a mock function with given fields:
func (_m *MockHandlerDependencyProvider) ArticleCategoryService() ArticleCategoryService {
	ret := _m.Called()

	var r0 ArticleCategoryService
	if rf, ok := ret.Get(0).(func() ArticleCategoryService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ArticleCategoryService)
		}
	}

	return r0
}

// MockHandlerDependencyProvider_ArticleCategoryService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArticleCategoryService'
type MockHandlerDependencyProvider_ArticleCategoryService_Call struct {
	*mock.Call
}

// ArticleCategoryService is a helper method to define mock.On call
func (_e *MockHandlerDependencyProvider_Expecter) ArticleCategoryService() *MockHandlerDependencyProvider_ArticleCategoryService_Call {
	return &MockHandlerDependencyProvider_ArticleCategoryService_Call{Call: _e.mock.On("ArticleCategoryService")}
}

func (_c *MockHandlerDependencyProvider_ArticleCategoryService_Call) Run(run func()) *MockHandlerDependencyProvider_ArticleCategoryService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandlerDependencyProvider_ArticleCategoryService_Call) Return(_a0 ArticleCategoryService) *MockHandlerDependencyProvider_ArticleCategoryService_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandlerDependencyProvider_ArticleCategoryService_Call) RunAndReturn(run func() ArticleCategoryService) *MockHandlerDependencyProvider_ArticleCategoryService_Call {
	_c.Call.Return(run)
	return _c
}

// ArticleService provides a mock function with given fields:
func (_m *MockHandlerDependencyProvider) ArticleService() ArticleService {
	ret := _m.Called()

	var r0 ArticleService
	if rf, ok := ret.Get(0).(func() ArticleService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ArticleService)
		}
	}

	return r0
}

// MockHandlerDependencyProvider_ArticleService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArticleService'
type MockHandlerDependencyProvider_ArticleService_Call struct {
	*mock.Call
}

// ArticleService is a helper method to define mock.On call
func (_e *MockHandlerDependencyProvider_Expecter) ArticleService() *MockHandlerDependencyProvider_ArticleService_Call {
	return &MockHandlerDependencyProvider_ArticleService_Call{Call: _e.mock.On("ArticleService")}
}

func (_c *MockHandlerDependencyProvider_ArticleService_Call) Run(run func()) *MockHandlerDependencyProvider_ArticleService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandlerDependencyProvider_ArticleService_Call) Return(_a0 ArticleService) *MockHandlerDependencyProvider_ArticleService_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandlerDependencyProvider_ArticleService_Call) RunAndReturn(run func() ArticleService) *MockHandlerDependencyProvider_ArticleService_Call {
	_c.Call.Return(run)
	return _c
}

// ArticleTagService provides a mock function with given fields:
func (_m *MockHandlerDependencyProvider) ArticleTagService() ArticleTagService {
	ret := _m.Called()

	var r0 ArticleTagService
	if rf, ok := ret.Get(0).(func() ArticleTagService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ArticleTagService)
		}
	}

	return r0
}

// MockHandlerDependencyProvider_ArticleTagService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArticleTagService'
type MockHandlerDependencyProvider_ArticleTagService_Call struct {
	*mock.Call
}

// ArticleTagService is a helper method to define mock.On call
func (_e *MockHandlerDependencyProvider_Expecter) ArticleTagService() *MockHandlerDependencyProvider_ArticleTagService_Call {
	return &MockHandlerDependencyProvider_ArticleTagService_Call{Call: _e.mock.On("ArticleTagService")}
}

func (_c *MockHandlerDependencyProvider_ArticleTagService_Call) Run(run func()) *MockHandlerDependencyProvider_ArticleTagService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandlerDependencyProvider_ArticleTagService_Call) Return(_a0 ArticleTagService) *MockHandlerDependencyProvider_ArticleTagService_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandlerDependencyProvider_ArticleTagService_Call) RunAndReturn(run func() ArticleTagService) *MockHandlerDependencyProvider_ArticleTagService_Call {
	_c.Call.Return(run)
	return _c
}

// AssetsService provides a mock function with given fields:
func (_m *MockHandlerDependencyProvider) AssetsService() AssetsService {
	ret := _m.Called()

	var r0 AssetsService
	if rf, ok := ret.Get(0).(func() AssetsService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(AssetsService)
		}
	}

	return r0
}

// MockHandlerDependencyProvider_AssetsService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssetsService'
type MockHandlerDependencyProvider_AssetsService_Call struct {
	*mock.Call
}

// AssetsService is a helper method to define mock.On call
func (_e *MockHandlerDependencyProvider_Expecter) AssetsService() *MockHandlerDependencyProvider_AssetsService_Call {
	return &MockHandlerDependencyProvider_AssetsService_Call{Call: _e.mock.On("AssetsService")}
}

func (_c *MockHandlerDependencyProvider_AssetsService_Call) Run(run func()) *MockHandlerDependencyProvider_AssetsService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandlerDependencyProvider_AssetsService_Call) Return(_a0 AssetsService) *MockHandlerDependencyProvider_AssetsService_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandlerDependencyProvider_AssetsService_Call) RunAndReturn(run func() AssetsService) *MockHandlerDependencyProvider_AssetsService_Call {
	_c.Call.Return(run)
	return _c
}

// MemberService provides a mock function with given fields:
func (_m *MockHandlerDependencyProvider) MemberService() MemberService {
	ret := _m.Called()

	var r0 MemberService
	if rf, ok := ret.Get(0).(func() MemberService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(MemberService)
		}
	}

	return r0
}

// MockHandlerDependencyProvider_MemberService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MemberService'
type MockHandlerDependencyProvider_MemberService_Call struct {
	*mock.Call
}

// MemberService is a helper method to define mock.On call
func (_e *MockHandlerDependencyProvider_Expecter) MemberService() *MockHandlerDependencyProvider_MemberService_Call {
	return &MockHandlerDependencyProvider_MemberService_Call{Call: _e.mock.On("MemberService")}
}

func (_c *MockHandlerDependencyProvider_MemberService_Call) Run(run func()) *MockHandlerDependencyProvider_MemberService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandlerDependencyProvider_MemberService_Call) Return(_a0 MemberService) *MockHandlerDependencyProvider_MemberService_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandlerDependencyProvider_MemberService_Call) RunAndReturn(run func() MemberService) *MockHandlerDependencyProvider_MemberService_Call {
	_c.Call.Return(run)
	return _c
}

// PasswordService provides a mock function with given fields:
func (_m *MockHandlerDependencyProvider) PasswordService() PasswordService {
	ret := _m.Called()

	var r0 PasswordService
	if rf, ok := ret.Get(0).(func() PasswordService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(PasswordService)
		}
	}

	return r0
}

// MockHandlerDependencyProvider_PasswordService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PasswordService'
type MockHandlerDependencyProvider_PasswordService_Call struct {
	*mock.Call
}

// PasswordService is a helper method to define mock.On call
func (_e *MockHandlerDependencyProvider_Expecter) PasswordService() *MockHandlerDependencyProvider_PasswordService_Call {
	return &MockHandlerDependencyProvider_PasswordService_Call{Call: _e.mock.On("PasswordService")}
}

func (_c *MockHandlerDependencyProvider_PasswordService_Call) Run(run func()) *MockHandlerDependencyProvider_PasswordService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandlerDependencyProvider_PasswordService_Call) Return(_a0 PasswordService) *MockHandlerDependencyProvider_PasswordService_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandlerDependencyProvider_PasswordService_Call) RunAndReturn(run func() PasswordService) *MockHandlerDependencyProvider_PasswordService_Call {
	_c.Call.Return(run)
	return _c
}

// SessionService provides a mock function with given fields:
func (_m *MockHandlerDependencyProvider) SessionService() SessionService {
	ret := _m.Called()

	var r0 SessionService
	if rf, ok := ret.Get(0).(func() SessionService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(SessionService)
		}
	}

	return r0
}

// MockHandlerDependencyProvider_SessionService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SessionService'
type MockHandlerDependencyProvider_SessionService_Call struct {
	*mock.Call
}

// SessionService is a helper method to define mock.On call
func (_e *MockHandlerDependencyProvider_Expecter) SessionService() *MockHandlerDependencyProvider_SessionService_Call {
	return &MockHandlerDependencyProvider_SessionService_Call{Call: _e.mock.On("SessionService")}
}

func (_c *MockHandlerDependencyProvider_SessionService_Call) Run(run func()) *MockHandlerDependencyProvider_SessionService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandlerDependencyProvider_SessionService_Call) Return(_a0 SessionService) *MockHandlerDependencyProvider_SessionService_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandlerDependencyProvider_SessionService_Call) RunAndReturn(run func() SessionService) *MockHandlerDependencyProvider_SessionService_Call {
	_c.Call.Return(run)
	return _c
}

// SlugifyService provides a mock function with given fields:
func (_m *MockHandlerDependencyProvider) SlugifyService() SlugifyService {
	ret := _m.Called()

	var r0 SlugifyService
	if rf, ok := ret.Get(0).(func() SlugifyService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(SlugifyService)
		}
	}

	return r0
}

// MockHandlerDependencyProvider_SlugifyService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SlugifyService'
type MockHandlerDependencyProvider_SlugifyService_Call struct {
	*mock.Call
}

// SlugifyService is a helper method to define mock.On call
func (_e *MockHandlerDependencyProvider_Expecter) SlugifyService() *MockHandlerDependencyProvider_SlugifyService_Call {
	return &MockHandlerDependencyProvider_SlugifyService_Call{Call: _e.mock.On("SlugifyService")}
}

func (_c *MockHandlerDependencyProvider_SlugifyService_Call) Run(run func()) *MockHandlerDependencyProvider_SlugifyService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandlerDependencyProvider_SlugifyService_Call) Return(_a0 SlugifyService) *MockHandlerDependencyProvider_SlugifyService_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandlerDependencyProvider_SlugifyService_Call) RunAndReturn(run func() SlugifyService) *MockHandlerDependencyProvider_SlugifyService_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockHandlerDependencyProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockHandlerDependencyProvider creates a new instance of MockHandlerDependencyProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockHandlerDependencyProvider(t mockConstructorTestingTNewMockHandlerDependencyProvider) *MockHandlerDependencyProvider {
	mock := &MockHandlerDependencyProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
