// Code generated by mockery v2.20.0. DO NOT EDIT.

package signup

import (
	context "context"
	model "{{ shortName }}/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// MockMemberService is an autogenerated mock type for the MemberService type
type MockMemberService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, data
func (_m *MockMemberService) Create(ctx context.Context, data model.MemberWithPassword) error {
	ret := _m.Called(ctx, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.MemberWithPassword) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockMemberService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockMemberService creates a new instance of MockMemberService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockMemberService(t mockConstructorTestingTNewMockMemberService) *MockMemberService {
	mock := &MockMemberService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
