// Code generated by mockery v2.20.0. DO NOT EDIT.

package update

import (
	model "cms/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTagService is an autogenerated mock type for the TagService type
type MockTagService struct {
	mock.Mock
}

// Update provides a mock function with given fields: ctx, data
func (_m *MockTagService) Update(ctx context.Context, data model.Tag) error {
	ret := _m.Called(ctx, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Tag) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockTagService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockTagService creates a new instance of MockTagService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockTagService(t mockConstructorTestingTNewMockTagService) *MockTagService {
	mock := &MockTagService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
