// Code generated by mockery v2.20.0. DO NOT EDIT.

package detail

import (
	model "cms/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockArticleService is an autogenerated mock type for the ArticleService type
type MockArticleService struct {
	mock.Mock
}

// FindBySlug provides a mock function with given fields: ctx, slug
func (_m *MockArticleService) FindBySlug(ctx context.Context, slug model.ArticleSlug) (model.Article, error) {
	ret := _m.Called(ctx, slug)

	var r0 model.Article
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ArticleSlug) (model.Article, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ArticleSlug) model.Article); ok {
		r0 = rf(ctx, slug)
	} else {
		r0 = ret.Get(0).(model.Article)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ArticleSlug) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockArticleService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockArticleService creates a new instance of MockArticleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockArticleService(t mockConstructorTestingTNewMockArticleService) *MockArticleService {
	mock := &MockArticleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
