// Code generated by mockery v2.20.0. DO NOT EDIT.

package detail

import (
	model "cms/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockArticleTagService is an autogenerated mock type for the ArticleTagService type
type MockArticleTagService struct {
	mock.Mock
}

// GetTagForArticle provides a mock function with given fields: ctx, articleID
func (_m *MockArticleTagService) GetTagForArticle(ctx context.Context, articleID model.ArticleID) ([]model.Tag, error) {
	ret := _m.Called(ctx, articleID)

	var r0 []model.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ArticleID) ([]model.Tag, error)); ok {
		return rf(ctx, articleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ArticleID) []model.Tag); ok {
		r0 = rf(ctx, articleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ArticleID) error); ok {
		r1 = rf(ctx, articleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockArticleTagService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockArticleTagService creates a new instance of MockArticleTagService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockArticleTagService(t mockConstructorTestingTNewMockArticleTagService) *MockArticleTagService {
	mock := &MockArticleTagService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
