// Code generated by mockery v2.20.0. DO NOT EDIT.

package detail

import (
	context "context"
	model "site/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// MockArticlesService is an autogenerated mock type for the ArticlesService type
type MockArticlesService struct {
	mock.Mock
}

// Article provides a mock function with given fields: ctx, slug
func (_m *MockArticlesService) Article(ctx context.Context, slug string) (*model.Article, error) {
	ret := _m.Called(ctx, slug)

	var r0 *model.Article
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Article, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Article); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Article)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockArticlesService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockArticlesService creates a new instance of MockArticlesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockArticlesService(t mockConstructorTestingTNewMockArticlesService) *MockArticlesService {
	mock := &MockArticlesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
