// Code generated by mockery v2.20.0. DO NOT EDIT.

package email

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockSessionService is an autogenerated mock type for the SessionService type
type MockSessionService struct {
	mock.Mock
}

// UpdateEmail provides a mock function with given fields: w, r, email
func (_m *MockSessionService) UpdateEmail(w http.ResponseWriter, r *http.Request, email string) error {
	ret := _m.Called(w, r, email)

	var r0 error
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, string) error); ok {
		r0 = rf(w, r, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockSessionService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockSessionService creates a new instance of MockSessionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockSessionService(t mockConstructorTestingTNewMockSessionService) *MockSessionService {
	mock := &MockSessionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
