// Code generated by mockery v2.20.0. DO NOT EDIT.

package articles

import (
	model "cms/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSlugifyService is an autogenerated mock type for the SlugifyService type
type MockSlugifyService struct {
	mock.Mock
}

type MockSlugifyService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSlugifyService) EXPECT() *MockSlugifyService_Expecter {
	return &MockSlugifyService_Expecter{mock: &_m.Mock}
}

// SlugifyArticle provides a mock function with given fields: ctx, name
func (_m *MockSlugifyService) SlugifyArticle(ctx context.Context, name string) model.ArticleSlug {
	ret := _m.Called(ctx, name)

	var r0 model.ArticleSlug
	if rf, ok := ret.Get(0).(func(context.Context, string) model.ArticleSlug); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(model.ArticleSlug)
	}

	return r0
}

// MockSlugifyService_SlugifyArticle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SlugifyArticle'
type MockSlugifyService_SlugifyArticle_Call struct {
	*mock.Call
}

// SlugifyArticle is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSlugifyService_Expecter) SlugifyArticle(ctx interface{}, name interface{}) *MockSlugifyService_SlugifyArticle_Call {
	return &MockSlugifyService_SlugifyArticle_Call{Call: _e.mock.On("SlugifyArticle", ctx, name)}
}

func (_c *MockSlugifyService_SlugifyArticle_Call) Run(run func(ctx context.Context, name string)) *MockSlugifyService_SlugifyArticle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSlugifyService_SlugifyArticle_Call) Return(_a0 model.ArticleSlug) *MockSlugifyService_SlugifyArticle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSlugifyService_SlugifyArticle_Call) RunAndReturn(run func(context.Context, string) model.ArticleSlug) *MockSlugifyService_SlugifyArticle_Call {
	_c.Call.Return(run)
	return _c
}

// SlugifyTag provides a mock function with given fields: ctx, name
func (_m *MockSlugifyService) SlugifyTag(ctx context.Context, name string) model.TagSlug {
	ret := _m.Called(ctx, name)

	var r0 model.TagSlug
	if rf, ok := ret.Get(0).(func(context.Context, string) model.TagSlug); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(model.TagSlug)
	}

	return r0
}

// MockSlugifyService_SlugifyTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SlugifyTag'
type MockSlugifyService_SlugifyTag_Call struct {
	*mock.Call
}

// SlugifyTag is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockSlugifyService_Expecter) SlugifyTag(ctx interface{}, name interface{}) *MockSlugifyService_SlugifyTag_Call {
	return &MockSlugifyService_SlugifyTag_Call{Call: _e.mock.On("SlugifyTag", ctx, name)}
}

func (_c *MockSlugifyService_SlugifyTag_Call) Run(run func(ctx context.Context, name string)) *MockSlugifyService_SlugifyTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSlugifyService_SlugifyTag_Call) Return(_a0 model.TagSlug) *MockSlugifyService_SlugifyTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSlugifyService_SlugifyTag_Call) RunAndReturn(run func(context.Context, string) model.TagSlug) *MockSlugifyService_SlugifyTag_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockSlugifyService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockSlugifyService creates a new instance of MockSlugifyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockSlugifyService(t mockConstructorTestingTNewMockSlugifyService) *MockSlugifyService {
	mock := &MockSlugifyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
