// Code generated by mockery v2.20.0. DO NOT EDIT.

package update

import (
	model "cms/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockArticleService is an autogenerated mock type for the ArticleService type
type MockArticleService struct {
	mock.Mock
}

// Update provides a mock function with given fields: ctx, data, tags
func (_m *MockArticleService) Update(ctx context.Context, data model.Article, tags []model.Tag) error {
	ret := _m.Called(ctx, data, tags)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Article, []model.Tag) error); ok {
		r0 = rf(ctx, data, tags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockArticleService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockArticleService creates a new instance of MockArticleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockArticleService(t mockConstructorTestingTNewMockArticleService) *MockArticleService {
	mock := &MockArticleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
